### ISSUE TITLE
Provide guidance on when / how to generate `package-lock.json`

### ISSUE THREAD

**Issue by choldgraf** [pradyunsg/sphinx-theme-builder#14]
### Description

When this package installs `npm` dependencies, it does so with a `--no-save` flag:

https://github.com/pradyunsg/sphinx-theme-builder/blob/10450cfeb65bc3610a6708ee731069c707978fef/src/sphinx_theme_builder/_internal/nodejs.py#L150

This means that dependencies aren't frozen into a `package-lock.json` file. As far as I can tell, it's not possible to run this command without the `--no-save` unless you did it manually with `stb npm install`.

It would be helpful if this package provided guidance for how authors can create `package-lock.json` (even if just telling people to do it manually with `stb npm install`)

**Comment by pradyunsg** [comment]
Hmm... Why did I add a --no-save!?

**Comment by choldgraf** [comment]
@pradyunsg maybe to prevent `package-lock.json` from getting over-written *every time* somebody installs? That was a big headache with the old version of the pydata theme. Newcomers would pip-install the theme locally and run the install command, and then it would create a huge `yarn.lock` diff. I think in general it's good to ask people to make an intentional act to update the lockfile rather than doing it automatically

**Comment by pradyunsg** [comment]
Well, I've removed the `--no-save` in 6313fefc480c775c293ca46975229d6f33500990. `npm` is smart, and doesn't regenerate the file if it already exists. Doing an `npm install` shouldn't affect the lockfile.
