### ISSUE TITLE
Python version should be >= 3.8 , since this package uses `Protocol`

### ISSUE THREAD

**Issue by AakashGfude** [pradyunsg/sphinx-theme-builder#15]
`Protocol` is imported in https://github.com/pradyunsg/sphinx-theme-builder/blob/main/src/sphinx_theme_builder/_internal/cli/__init__.py#L3.

But it is a feature introduced in python v3.8 https://docs.python.org/3/library/typing.html#typing.Protocol.

The `pyproject.toml` file at present accepts python v3.7 https://github.com/pradyunsg/sphinx-theme-builder/blob/main/pyproject.toml#L24

**Comment by pradyunsg** [comment]
Python 3.7 compatibility was fixed in https://sphinx-theme-builder.readthedocs.io/en/latest/changelog/#a15.
