### ISSUE TITLE
Should the assets sources still be included in the wheel?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pradyunsg/sphinx-theme-builder#16]
Checking the new wheel for pydata-sphinx-theme 0.8.0 (https://pypi.org/project/pydata-sphinx-theme/0.8.0/#files), I noticed that it still includes the `pydata_sphinx_theme/assets/` scripts and styles (the original source), in addition to the compiled files located at `pydata_sphinx_theme/theme/pydata_sphinx_theme/static/`. 

Just wondering if that is intentional?

**Comment by pradyunsg** [comment]
Yes, it is. That is intended to, in the future, make it possible to derive from the assets of a theme and extend them; without needing to include the compiled assets of the theme.
