### ISSUE TITLE
Allow relaxing the NodeJS version check, when `STB_USE_SYSTEM_NODE` is used

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/sphinx-theme-builder#32]
### What's happening?

Certain redistributors don't like that they need to provide a specific version of NodeJS, down to the exact patch version, for building Sphinx themes with sphinx-theme-builder.

This restriction exists so that theme authors don't encounter pain due to redistributors who mess things up, ignoring the details of how the package works because "the build is successful in our build system" (which is *not* the same as "everything about the package works the same as upstream, and is supported by them"). This is especially true for Sphinx themes, since the failure modes are "things look wrong" rather than "the compiler raised an exception" and there's many components involved here -- the JS tooling use to build it, the Python build time dependencies, the Python runtime dependencies (including Sphinx's dependencies, whose versions change the rendered markup) and the interactions between all of them.

### Reproducer

1. Ensure you have NodeJS 16.x as the first entry on `PATH`.
2. Run `STB_USE_SYSTEM_NODE=true pip install https://github.com/pradyunsg/furo/archive/refs/tags/2022.06.21.zip`
3. See a failure due to a mismatch.

### Expectation

The restriction should be, with another flag, relaxed to enforce the major version and a minimum patch version of NodeJS. This has a low-enough risk of meddling horribly with the JS-based build, that it should not result in additional need for the theme authors to deal with difficult-to-diagnose issues because a redistributor broke their package.

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/pradyunsg/furo/blob/main/CODE_OF_CONDUCT.md).

**Comment by pradyunsg** [comment]
x-ref: https://github.com/pradyunsg/sphinx-theme-builder/discussions/31

**Comment by pradyunsg** [comment]
Done and released in a15.

See https://sphinx-theme-builder.readthedocs.io/en/latest/build-process/#appendix-controlling-nodejs-installation. If this doesn't work, lemme know! :)

**Comment by dvzrv** [comment]
@pradyunsg Hi! I'm currently trying to package sphinx-book-theme for Arch Linux and the introduced environment variables mentioned in https://sphinx-theme-builder.readthedocs.io/en/latest/build-process/#appendix-controlling-nodejs-installation are not enough:

```
* Getting build dependencies for wheel...
* Building wheel...
[stb] # nodeenv does not exist.
[stb] # Generating new nodeenv with NodeJS 16.13.2!
[stb] # Will use system nodeJS.
[stb] $ python -m nodeenv --node=system --prebuilt --clean-src /build/python-sphinx-book-theme/src/sphinx_book_theme-1.0.0/.nodeenv
which: no nodejs in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
[stb] (nodeenv) $ node --version
v16.19.1
[stb] # The node version is not the expected one.
[stb] # The generated assets may be broken even if the build succeeds.
[stb] # Continuing anyway - `STB_RELAX_NODE_VERSION_CHECK` is truthy.
error: node-version-mismatch

× The node version is not compatible with the expected version.
╰─> Minor version is lower than the value declared in the theme.
    See above for the expected and actual version.

hint: You need to use a compatible version of NodeJS to build the theme.
link: https://sphinx-theme-builder.rtfd.io/errors/#node-version-mismatch

ERROR Backend subprocess exited when trying to invoke build_wheel
```

If I have to patch the pyproject.toml file anyways, I don't think there is much use in having `STB_RELAX_NODE_VERSION_CHECK` if it only relaxes check on the patch level version.

**Comment by pradyunsg** [comment]
The behaviour changes to...

> ensuring that it has the same major version and an equal-or-higher minor version. The patch version is ignored.

You're on an older version of NodeJS (16.3.2, 2021-06-02), which is likely not forwards-compatible with the one declared in the theme (16.19.1, 2023-02-16).
