### ISSUE TITLE
Sphinx-theme-template-stable.zip doesn't exist

### ISSUE THREAD

**Issue by patrickmineault** [pradyunsg/sphinx-theme-builder#34]
### What's happening?

When running `stb new blank-theme`, the package will try to download `https://github.com/pradyunsg/sphinx-theme-template/archive/refs/heads/sphinx-theme-template-stable.zip` to make a template. However, this file doesn't exist.

### Reproducer

1. pip install from head, e.g. `pip install git+https://github.com/pradyunsg/sphinx-theme-builder.git`
2. Run `stb new blank-theme` in the repository root.
3. Error:

```
Zip repository https://github.com/pradyunsg/sphinx-theme-template/archive/refs/heads/sphinx-theme-template-stable.zip is not a valid zip archive:
error: cookiecutter-failed

× Cookiecutter failed to generate the project.
╰─> Exit code: 1
```

### Expectation

The file should exist or the link should be corrected.

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/pradyunsg/furo/blob/main/CODE_OF_CONDUCT.md).

**Comment by pradyunsg** [comment]
This is expected.

https://sphinx-theme-builder.readthedocs.io/en/latest/errors/#cookiecutter-failed

Consolidating into #11.
