### ISSUE TITLE
Better document which node is used / how it interacts with existing environments

### ISSUE THREAD

**Issue by jorisvandenbossche** [pradyunsg/sphinx-theme-builder#6]
My current understanding is that: 

1) It will first check if the "system" node (I suppose what is available if you run `node --version` in a console on your system) has the exact same version as the required version (`node-version` in pyproject.toml), and if those match, use the system node.
2) If those version don't match, `nodeenv` will install the required node version

Is that correct? 

But in both cases `nodeenv` will still create a `.nodeenv` directory? (only in the first case it seems that the node executable in there is then basically a symlink to the system one. I suppose this is logic that lives in the `nodeenv` package)

**Comment by pradyunsg** [comment]
Yup. This package needs a bunch of documentation.

**Comment by pradyunsg** [comment]
Closing this out for now. This is much easier to explain now, and I'll address this as part of addressing the general lack of documentation.
