### ISSUE TITLE
Providing the required node version in a conda environment doesn't work

### ISSUE THREAD

**Issue by jorisvandenbossche** [pradyunsg/sphinx-theme-builder#7]
Somewhat related to https://github.com/pradyunsg/sphinx-theme-builder/issues/6: I tried out the workflow of using a conda environment, and installing the exact required version of node in that environment (in the idea that the conda-provided node would be detected as matching "system" node, and thus used by sphinx-theme-builder / nodeenv). But it seems this is not fully working.

`docs-theme2` is a conda env in which I installed the exact node version that is required (+ all dependencies to build the demo docs + sphinx-theme-builder):

```
(docs-theme2) ~/pydata-sphinx-theme$ stb serve docs/
[stb] Invoking sphinx-autobuild to run.
[sphinx-autobuild] pre-build
[sphinx-autobuild] > /home/joris/miniconda3/envs/docs-theme2/bin/python3.9 -m sphinx_theme_builder compile
[stb] # nodeenv does not exist.
[stb] # Generating new nodeenv with NodeJS 14.17.4!
[stb] # Will use system nodeJS, since version matches.
[stb] $ python -m nodeenv --node=system /home/joris/scipy/repos/pydata-sphinx-theme/.nodeenv
[stb] (nodeenv) $ node --version
v10.19.0
error: nodeenv-version-mismatch

× The `nodeenv` for this project is unhealthy.
╰─> There is a mismatch between what is present in the environment (v10.19.0) and the expected version of NodeJS (v14.17.4).

hint: Deleting the .nodeenv directory and trying again may work.

Link: https://sphinx-theme-builder.rtfd.io/errors/#nodeenv-version-mismatch
Command exited with exit code: 3
```

So it detects that the conda installed node version is matching the required version, but then nodeenv links to the actual system provided one (apparently I have a system wide node with version 10.19.0), and not the conda provided node. Resulting in a "broken" workflow. This might also be an issue to open with nodeenv.

Note: I am not sure how useful it is to actually try this (I am personally happy with the workflow to let nodeenv manage the node installation), but it would be good to know if this could work or will never work, to ensure we can document this for people using conda (and potentially having node installed in their environment)
(note: I personally don't want to use this workflow myself (I am happy with the node that nodeenv installs), but some users might want to

**Comment by kapooramit** [comment]
I am getting the same error. So in other words - I am unable to create a wheel package. Is there a workaround?

**Comment by kapooramit** [comment]
I fixed the version but still no go. Please help. This is not letting me move ahead:
Ok. I tried to build wheel and still getting the same error. I have fixed the version but still. What do I need to do?
````
D:\furo>python -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (sphinx-theme-builder >= 0.2.0a10)
* Getting dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (sphinx-theme-builder >= 0.2.0a10)
* Getting dependencies for wheel...
* Building wheel...
[stb] # nodeenv does not exist.
[stb] # Generating new nodeenv with NodeJS 16.13.0!
[stb] # Could not find a `node` executable.
[stb] $ python -m nodeenv --node=16.13.0
C:\Users\<username>\AppData\Local\Temp\build-via-sdist-e99fn80c\furo-2021.11.23.dev1\.nodeenv
 * Install prebuilt node (16.13.0) ..... done.
You do not have sufficient privilege to perform this operation.
You do not have sufficient privilege to perform this operation.
Error: Failed to create nodejs.exe link
[stb] (nodeenv) $ node --version
error: nodeenv-unhealthy-file-not-found

× The `nodeenv` for this project is unhealthy.
╰─> None

hint: Deleting the .nodeenv directory and trying again may work.

Link: https://sphinx-theme-builder.rtfd.io/errors/#nodeenv-unhealthy-file-not-found

ERROR Backend subproccess exited when trying to invoke build_wheel
````

**Comment by pradyunsg** [comment]
@jorisvandenbossche What OS are you on? I'm guessing this is a Linux environment?

@kapooramit I'll respond over on https://github.com/pradyunsg/furo/discussions/330.

**Comment by jorisvandenbossche** [comment]
Yes, Linux (Ubuntu 20.04)

**Comment by kapooramit** [comment]
Thank you! @pradyunsg! I love your theme (furo) and from the last couple of days - reading here and there to be able to start using it as a base and develop my custom theme on it. But I am unable to setup the dev/test environment. I will wait for your response.

**Comment by pradyunsg** [comment]
I don't have a Windows machine to try this on right now, and am on an OSS hiatus; but if someone is interested in installing a development version of sphinx-theme-builder; running pip with `--no-build-isolation` and figuring out what exactly is going wrong, that would be welcome.

**Comment by jorisvandenbossche** [comment]
@kapooramit it might be worth opening a separate issue, as I think what you are seeing is another / general issue on Windows (which @drammock is also seeing at https://github.com/pydata/pydata-sphinx-theme/issues/523#issuecomment-1002212973). There seems to be a problem with creating the node env ("Error: Failed to create nodejs.exe link"). 
While the issue I opened originally is about finding the wrong node env inside a conda environment, if you have both node installed in that environment as a global one.

**Comment by pradyunsg** [comment]
I've made a bunch of changes to how this works in https://github.com/pradyunsg/sphinx-theme-builder/compare/818d231c406ce98f02952025ea1c03ba80d6fa24..32377e2ad7179b430b8fb3ae65950d962cf8d21a

1. Windows does not support `system` nodeenv (that's a nodeenv limitation)
2. This will now use a dedicated isolated nodeenv, unless a specific environment variable is set.

That should make this less painful (it won't try + fail to use the conda node) but does not solve the underlying issue here; which I haven't been able to figure out.

**Comment by pradyunsg** [comment]
Released the above changes in 0.2.0a13!

**Comment by bollwyvl** [comment]
yeah, to package https://github.com/pydata/pydata-sphinx-theme/pull/562 we'll need to figure out how to build this package for conda-forge and _not_ have it randomly install an extra version of node. other downstreams that can provide node will have similar challenges.

another option would be to emulate `flit` and continue to pragmatically support building legacy-compatible `sdist` packages that contain the built JS/CSS and a generated `setup.py`/`setup.cfg`, and put off having to package this until it's ready to go (#11).

**Comment by pradyunsg** [comment]
You can set `STB_USE_SYSTEM_NODE=1` in the environment, and it'll use the system node version. It does require that the *exact* node version be available.

**Comment by pradyunsg** [comment]
Given that Furo is in the conda-forge feedstock, I think things work just fine with `STB_USE_SYSTEM_NODE`.
