### ISSUE TITLE
cookiecutter failed

### ISSUE THREAD

**Issue by kapooramit** [pradyunsg/sphinx-theme-builder#8]
Hi
I am getting this error when trying the **stb new _themename_** . 
What am I missing?

**Comment by kapooramit** [comment]
The error changes because I installed cookiecutter separately but still no go:

````
https://github.com/pradyunsg/sphinx-theme-template/archive/refs/heads/sphinx-theme-template-stable.zip
Zip repository https://github.com/pradyunsg/sphinx-theme-template/archive/refs/heads/sphinx-theme-template-stable.zip is not a valid zip archive:
error: cookiecutter-failed

× Cookiecutter failed to generate the project.
╰─> Exit code: 1

note: cookiecutter's failure output is available above.
hint: @pradyunsg might still need to write/update the supporting cookiecutter template. 😅

Link: https://sphinx-theme-builder.rtfd.io/errors/#cookiecutter-failed
````

**Comment by pradyunsg** [comment]
> hint: @pradyunsg might still need to write/update the supporting cookiecutter template. 😅

As it says, I haven't written the relevant cookecutter template yet which is why this command won't work. I don't think I need a tracking issue for implementing this, so I'll go ahead and close this.
